### ISSUE TITLE
Does vagrant-vcloudair support ondemand vcloudair accounts? 

### ISSUE THREAD

**Issue by cathcartd** [frapposelli/vagrant-vcloudair#6]
When doing a `vagrant up` I keep getting:

```
ERROR vagrant: The specified Service cannot be found, please verify your 'cloud_id' and/or 'vdc_name' parameters.
```

Comparing [vagrant-vcloudair's call](https://github.com/gosddc/vagrant-vcloudair/blob/master/lib/vagrant-vcloudair/driver/meta.rb#L58) with [pyvcloud's call](https://github.com/vmware/pyvcloud/blob/f7145297614f8809e3e860a95fd83fa9aff9bf3f/pyvcloud/vcloudair.py#L153) looks like vagrant-vcloudair doesn't support login flow for ondemand accounts? 

`vagrant up --debug` shows the response to the `/vchs/services` api call is empty:

``` xml
<?xml version="1.0"?>
<Services xmlns="http://www.vmware.com/vchs/v5.6" xmlns:tns="http://www.vmware.com/vchs/v5.6" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="application/xml;class=vnd.vmware.vchs.servicelist" href="https://vchs.vmware.com/api/vchs/services"/>
```

**Comment by frapposelli** [comment]
Sorry but currently this plugin only supports the subscription API

**Comment by mkamlesh** [comment]
I am also getting the same error while trying to interact with vCloudAir instance through Vagrant. 

"vca status" actually shows settings as follows:
host             | https://vca.vmware.com 
org_url         | https://<region>.vchs.vmware.com/api/compute/api/sessions

Are you planning to provide the fix for this issue? 

Is there any other alternative that I can use to get vagrant deploy VMs in vCloudAir's Virtual Private Cloud?
